// <auto-generated />
namespace CCM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addnewcolumnsPatientMedicalHistory_MedicationRx_DiscontinueMedicine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnewcolumnsPatientMedicalHistory_MedicationRx_DiscontinueMedicine));
        
        string IMigrationMetadata.Id
        {
            get { return "201906191405034_addnewcolumnsPatientMedicalHistory_MedicationRx_DiscontinueMedicine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
