// <auto-generated />
namespace CCM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CCMCycleStatus_ClaimSubmission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CCMCycleStatus_ClaimSubmission));
        
        string IMigrationMetadata.Id
        {
            get { return "201911072013474_CCMCycleStatus_ClaimSubmission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
