// <auto-generated />
namespace CCM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcolumnsPatientProfile_UrgencyContact_AddNewTablesPatientProfile_ProfesionalCareProviderANDPatientProfile_DieseaseState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcolumnsPatientProfile_UrgencyContact_AddNewTablesPatientProfile_ProfesionalCareProviderANDPatientProfile_DieseaseState));
        
        string IMigrationMetadata.Id
        {
            get { return "201906181405585_addcolumnsPatientProfile_UrgencyContact_AddNewTablesPatientProfile_ProfesionalCareProviderANDPatientProfile_DieseaseState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
