// <auto-generated />
namespace CCM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserTicketGeneration_Update_And_AddASSIGNEETICKET : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserTicketGeneration_Update_And_AddASSIGNEETICKET));
        
        string IMigrationMetadata.Id
        {
            get { return "201910291733351_UserTicketGeneration_Update_And_AddASSIGNEETICKET"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
