// <auto-generated />
namespace CCM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Patient_PatientsPreLiasons_relationShip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Patient_PatientsPreLiasons_relationShip));
        
        string IMigrationMetadata.Id
        {
            get { return "202001301945512_Patient_PatientsPreLiasons_relationShip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
