// <auto-generated />
namespace CCM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Patients_PreLiaisonsId_Coloumn_AddedIn_patientsHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Patients_PreLiaisonsId_Coloumn_AddedIn_patientsHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "202001302032372_Patients_PreLiaisonsId_Coloumn_AddedIn_patientsHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
