// <auto-generated />
namespace CCM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class G0506patientupdatetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(G0506patientupdatetable));
        
        string IMigrationMetadata.Id
        {
            get { return "202003062150460_G0506patientupdatetable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
