// <auto-generated />
namespace CCM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PatientsProfileConcent_ImageAndNote_Relation_BillingCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PatientsProfileConcent_ImageAndNote_Relation_BillingCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202001311728205_PatientsProfileConcent_ImageAndNote_Relation_BillingCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
