// <auto-generated />
namespace CCM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _AddedtableRpm_PatientDeviceReading : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_AddedtableRpm_PatientDeviceReading));
        
        string IMigrationMetadata.Id
        {
            get { return "202004281600499__AddedtableRpm_PatientDeviceReading"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
