// <auto-generated />
namespace CCM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _updatedatatype_Patients_PreLiaisons : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_updatedatatype_Patients_PreLiaisons));
        
        string IMigrationMetadata.Id
        {
            get { return "202002051943388__updatedatatype_Patients_PreLiaisons"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
